name: gardproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.14.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  camera: ^0.10.5+9
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  http_parser: ^4.1.2
  google_sign_in: ^7.1.0
  flutter_screenutil: ^5.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/design.png
    - images/IMG_2748.PNG
    - images/Logo1.png
    - images/Logo (1).png
    - images/adele-payman-2oYMwuFgnTg-unsplash_1.jpg
    - images/eric-prouzet-VEhUoO67mOk-unsplash.jpg
    - images/james-baltz-yihX4Rq-JsI-unsplash.jpg
    - images/Sent_Message-bro_1.png
    - images/Frame_30.png
    - images/Two_factor_authentication-bro_1.png
    - images/Frame_31.png
    - images/Frame_34.png
    - images/image_9.png
    - images/photo_2026-05-08_15-27-27.jpg
    - images/photo_2026-05-08_15-27-29.jpg
    - images/photo_2026-05-08_15-27-31.jpg
    - images/image_10.png
    - images/photo_2026-05-08_15-27-33.jpg
    - images/photo_2026-05-08_15-27-35.jpg
    - images/photo_2026-05-08_15-27-36.jpg
    - images/photo_2026-05-08_15-27-38.jpg
    - images/photo_2026-05-08_15-27-39.jpg
    - images/photo_2026-05-08_15-27-41.jpg
    - images/photo_2026-05-08_15-27-42.jpg
    - images/photo_2026-05-08_15-27-44.jpg
    - images/photo_2026-05-08_15-27-45.jpg
    - images/photo_2026-05-08_15-27-46.jpg
    - images/photo_2026-05-08_15-27-48.jpg
    - images/photo_2026-05-08_15-27-49.jpg
    - images/photo_2026-05-08_15-27-50.jpg
    - images/hugeicons--home-01 (1).svg
    - images/si--notifications-alt-fill.svg
    - images/mage--scan.svg
    - images/fluent--weather-hail-day-24-regular.svg
    - images/ph--flashlight-light.svg
    - images/hugeicons--notification-01.svg
    - images/logos--facebook.svg
    - images/devicon--google.svg
    - images/circum--mobile-3.svg
    - images/ic--round-apple.svg
    - images/material-symbols--download.svg
    - images/bitcoin-icons--share-outline.svg
    - images/mi--drop.svg
    - images/hugeicons--plant-02.svg
    - images/solar--logout-2-line-duotone.svg
    - images/humbleicons--logout.svg
    - images/healthicons--yes-outline.svg
    - images/f7--cloud-rain.svg
    - images/cbi--garden-irrigation.svg
    - images/ph--drop.svg
    - images/mdi--leaf.svg
    - images/quill--eye.svg
    - images/hugeicons--uv-02.svg
    - images/solar--wind-bold.svg
    - images/line-md--paint-drop-half-filled.svg
    - images/mdi--bell-outline.svg
    - images/streamline--leaf-remix.svg
    - images/fa7-solid--shield-heart (1).svg
    - images/lucide--pen-line.svg
    - images/covid--personal-hygiene-hand-liquid-soap.svg
    - images/streamline-emojis--leaf-fluttering-in-wind.svg
    - images/f7--person.svg
    - images/1618201e616f4a40928c403f222d7562.jpg
    - images/Subtle Chart Graphic.png
    - assets/splash/mock/weather_mock.json
    - assets/splash/mock/dashboard.json
    - assets/splash/mock/notifications.json
    - assets/splash/mock/recommendation.json
    - assets/splash/mock/scan_overview.json
    - assets/splash/mock/scan_result.json
    

    - assets/splash/Logo (1).png

flutter_native_splash:
  color: "#111814"
  image: assets/splash/Logo (1).png
  android: true
  ios: true
  web: false
  android_12:
    color: "#111814"
    image: assets/splash/Logo (1).png