# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIW2G2QXgTJlzxAzL0SLwI1JgZnY67M2
"""

import json
import numpy as np
import tensorflow as tf

from io import BytesIO
from PIL import Image
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware

MODEL_PATH = "tomato_final_model.keras"
CLASS_NAMES_PATH = "class_names.json"

img_height = 256
img_width = 256


app = FastAPI(
    title="Tomato Disease Detection API",
    description="AI API for tomato leaf disease classification using EfficientNetV2S and TTA",
    version="1.0.0"
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


model = tf.keras.models.load_model(MODEL_PATH, compile=False)

with open(CLASS_NAMES_PATH, "r") as f:
    classes = json.load(f)


def clean_class_name(name):
    name = name.replace("Tomato___", "")
    name = name.replace("_", " ")

    if name.lower() == "healthy":
        return "Healthy"

    return name


def preprocess_image(image_bytes):
    try:
        image = Image.open(BytesIO(image_bytes)).convert("RGB")

        img_array = np.array(image, dtype=np.float32)
        img_array = tf.image.resize(img_array, [img_height, img_width])

        # نفس النوت بوك:
        # مفيش قسمة على 255
        # لأن EfficientNetV2S معمول بـ include_preprocessing=True
        img_batch = tf.expand_dims(img_array, axis=0)

        return img_batch

    except Exception:
        raise HTTPException(
            status_code=400,
            detail="Invalid image file."
        )


def predict_batch_tta(model, images):
    tta_images = []

    # Original image
    tta_images.append(images)

    # Horizontal flip
    tta_images.append(tf.image.flip_left_right(images))

    # Brightness adjustment
    tta_images.append(tf.image.adjust_brightness(images, delta=10.0))

    # Contrast adjustment
    tta_images.append(tf.image.adjust_contrast(images, contrast_factor=1.1))

    # Slight crop and resize
    cropped = tf.image.central_crop(images, central_fraction=0.9)
    cropped = tf.image.resize(cropped, (img_height, img_width))
    tta_images.append(cropped)

    predictions = []

    for aug_images in tta_images:
        preds = model(aug_images, training=False)
        predictions.append(preds)

    avg_predictions = tf.reduce_mean(tf.stack(predictions), axis=0)

    return avg_predictions


@app.get("/")
def root():
    return {
        "success": True,
        "message": "Tomato Disease Detection API is running with TTA."
    }


@app.get("/health")
def health_check():
    return {
        "success": True,
        "message": "AI service is healthy."
    }


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(
            status_code=400,
            detail="Only image files are allowed."
        )

    image_bytes = await file.read()

    if len(image_bytes) == 0:
        raise HTTPException(
            status_code=400,
            detail="Empty image file."
        )

    img_batch = preprocess_image(image_bytes)

    # نفس Gradio في النوت بوك
    predictions = predict_batch_tta(model, img_batch).numpy()[0]

    predicted_index = int(np.argmax(predictions))
    confidence = float(predictions[predicted_index]) * 100

    raw_class_name = classes[predicted_index]
    disease_name = clean_class_name(raw_class_name)

    is_healthy = disease_name.lower() == "healthy"

    return {
        "success": True,
        "model": "EfficientNetV2S",
        "predictionMethod": "TTA",
        "predictedClass": raw_class_name,
        "diseaseName": disease_name,
        "confidence": round(confidence, 2),
        "isHealthy": is_healthy
    }